### PR TITLE
Added ability to use custom windows

### PR DESCRIPTION
**Pull request by euri10**
This PR adds the possibility to use custom window times on the SlidingRedisBackend.

I implemented that using a new `custom` attribute on the `Rule` object that is a list of `LimitFrequency` objects.
If you have for instance LimitFrequency(limit=2, granularity=12) it would limit to 2 calls every 12 seconds.

### CODE REVIEW

**Comment by abersheeran** [comment]
I do have the idea of adding this kind of rule. Thank you very much for your PR.

I think this is better as a independent rule. Rename `Rule` to `FixedRule`, and let `LimitFrequency` and it as two different rules, what do you think?

**Comment by euri10** [comment]
> I do have the idea of adding this kind of rule. Thank you very much for your PR.
> 
> I think this is better as a independent rule. Rename `Rule` to `FixedRule`, and let `LimitFrequency` and it as two different rules, what do you think?

I have no preference. Now you mention that possibility I had not thought of I prefer it :)
I'll try adapt the PR as soon as possible in that direction

**Comment by abersheeran** [comment]
I suddenly thought of a question. If I want to control with multiple different time frequencies at the same time, how should I implement it?

**Comment by euri10** [comment]
> I suddenly thought of a question. If I want to control with multiple different time frequencies at the same time, how should I implement it?

in current's implementation `custom` accepts a list of `LimitFrequency` so you would just pass multiple ones.
I'll update with your comments asap

**Comment by euri10** [comment]
@abersheeran I think this is in a reviewable shape

however I added the retry-after logic to it, and I also somewhat modified / added things to the CI, so should you prefer I can separate the PR into 
1. CI stuff
2. custom windows stuff
3. retry-after stuff

I think that even if you prefer to split it there is some interest in having that as a basis to discuss the design, let me know your thoughts when you get time, I can also drop comments when things are not clear for you

for the point 1. CI stuff, I:
* added black, isort and flake8 checks
* dropped pytest-cov for pure coverage and corrected spots where coverage was week (added a few tests for that and / or increased # of parametric inputs in existing tests )
* added types where it was missing, I didn't yet added a CI check for it as there are still 3 or 4 errors that could be fixed. But those errors would / could be solved discussing the design first (mostly they are Liskov principle issues where I have more types in subclasses and less in the base class.. )
* added test for py3.9 and redis 6

**Comment by abersheeran** [comment]
I think we should do it step by step:

1. Add tests for Python3.9 (maybe 3.10) and Redis6
2. Add code format and static checking (if necessary, you can remove pytest-cov)
3. Redesign the code interface (this is a big job)

Then, when we do the third step, we can have a good code check and sufficient testing to verify its correctness. 

By the way, I think this should be divided into multiple PRs, and each part of it should be merged into the Master branch.

**Comment by euri10** [comment]
Sounds good yes, I'll close this and do the split ASAP !!

**Pull request closed without merging**
