### PR TITLE
Switch to redis-py

### PR DESCRIPTION
**Pull request by euri10**
Replaces https://github.com/abersheeran/asgi-ratelimit/pull/50

### CODE REVIEW

**Comment by euri10** [comment]
one thing to note, I'm no pro and not following too closely those libs but it seems StrictRedis is an alias to Redis so we may decide to switch to using Redis instead in the redis.asyncio.client module

**Comment by euri10** [comment]
I honestly dont understand at all the CI failure

**Comment by abersheeran** [comment]
> I honestly dont understand at all the CI failure

I found this: https://stackoverflow.com/questions/69528842/an-error-while-trying-to-execute-tests-on-python-3-10-with-pytest

**Comment by euri10** [comment]
> > I honestly dont understand at all the CI failure
> 
> I found this: https://stackoverflow.com/questions/69528842/an-error-while-trying-to-execute-tests-on-python-3-10-with-pytest

I lacked google skills on this one thanks for the link !

**Pull request merged**
